server:
  port: 8800

spring:
  data:
    mongodb:
      host: mongodb-finance
      port: 27017
      username: ${MONGO_FINANCE_USER}
      password: ${MONGO_FINANCE_PASSWORD}
      authentication-database: admin