server:
  port: 9999

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: iam-service
              uri: http://localhost:8888
              predicates:
                - Path=/api/v1/iam/**
            - id: user-service
              uri: http://localhost:8000
              predicates:
                - Path=/api/v1/users/**
            - id: finance-service
              uri: http://localhost:8800
              predicates:
                - Path=/api/v1/finances/**
            - id: subscription-service
              uri: http://localhost:8900
              predicates:
                - Path=/api/v1/subscriptions/**
            - id: wallet-service
              uri: http://localhost:8200
              predicates:
                - Path=/api/v1/wallets/**
            - id: wallet-ws
              uri: http://localhost:8200
              predicates:
                - Path=/ws-wallet/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marketsync-client


frontend-url: http://localhost:4200

jwk-uri: http://localhost:8080/realms/marketsync-client/protocol/openid-connect/certs

internal-jwt:
  issuer: marketsync-gateway
  ttl-seconds: 90
  audience: marketsync-internal
  public-key-pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HglAoDsfRTORBkzAAQk
    nfhPoINcSZKOtvqH3mNSKYfXGUcRf0JVPONbMaLbC391N8quD8MkXXOr703mp60v
    cvuRH4zsAQ/4kAitdMvEeDvzWqjVWAx61B19byQmVlC9D24kab36TcK66MrvrBpt
    nm6xq4V6MfN0c+ETBKs3a5AmYDJYR6BTjkyyv72okYlc5RdW52I+p8oQQCxzv9nH
    v87AsUuWHMqedf8uVetACwyMrK1kC/4LbNW5z9M5q8CIg1H07oZxZ/KE0N9yVvyc
    BB03TRXk+WvG2DQ7g+2ECEt8uhuhOB/3lhiaMjPYLkfKyfgs4pFGCTEwDhAP6jm+
    EQIDAQAB
    -----END PUBLIC KEY-----
  private-key-pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD4eCUCgOx9FM5E
    GTMABCSd+E+gg1xJko62+ofeY1Iph9cZRxF/QlU841sxotsLf3U3yq4PwyRdc6vv
    TeanrS9y+5EfjOwBD/iQCK10y8R4O/NaqNVYDHrUHX1vJCZWUL0PbiRpvfpNwrro
    yu+sGm2ebrGrhXox83Rz4RMEqzdrkCZgMlhHoFOOTLK/vaiRiVzlF1bnYj6nyhBA
    LHO/2ce/zsCxS5Ycyp51/y5V60ALDIysrWQL/gts1bnP0zmrwIiDUfTuhnFn8oTQ
    33JW/JwEHTdNFeT5a8bYNDuD7YQIS3y6G6E4H/eWGJoyM9guR8rJ+CzikUYJMTAO
    EA/qOb4RAgMBAAECggEAFFDpkMf3Hj6ZY3zOfFu6XT7IjvqyrPLab7hyK9NB7HKm
    mjLjCb1kIBGEez1iTPE/5b8RJqmJc4kx16QuXgs1eCC88+AXS3pxc+B7w1MmdkDL
    o//uSs/haq7bGt9xMYlSPhzexhUiLmHD2+U8/dze1e+d4CUOsd8iyFdQ0WbJBia2
    1+EVzs+9a4RBuW46ql2NcEpiGa5MxEngXwxLYOZlr1RZeofiOe55h4hpWhLgHS+8
    1E9+YljeNjooVCm10jmMTd4Wp4Q8Uif4pCduxVmesfck2Kx33Kqkg/i/an8MwpBC
    tzKN/t+xPTKWCyidSFiq1yp7kFYJhDu/Xc4DnhTa6QKBgQD99Vw4TAKNegT6nWYL
    E3arl1Xwqc0uQX+N3q1kibF7Nh3ouP+63bA6/2C5xJJKjSpp+LQcRGY1QsygAqhb
    xUkot+bDm93uYlRmmuLvcCDx/1Xtds+sZS3NsSqR4RrEfSkFlYP0g8ZPeA86x5Ms
    R3Jc40ip/YjNlzYY/MHDY//BqQKBgQD6d3zkoqFHrqtmJV27SWFkCyx7mSOOjZb+
    MHkMqIgj8Yfc+VL02A7e+zL28TS82nUcHSxh+Rw1QLE/q6P8NatCwJvwPpSrcYYf
    HNL7XGjsDi+CXJkkXtTF/NXSZiWIiG2wdIXAF4x8/Tf4XQvjzfI1uLZLzXhQr08v
    PQxT104qKQKBgQC5a63bhNPQTCjaepWIvLtGaYZb4v5mKXhiMxVSdJ5bIZYQ1xIQ
    c9A6Iz+SIw3U1OEE4otOoDon5Q/WPFqENrVFv5ADfgg6Bx0slSXgQHQtfIpWiQr0
    CiO5LQOx4zNSBzguVY40twnR+AzWk+TGzZuYanIhe3Wo9iCPeexXJuoTkQKBgHzd
    VMYmzYCO86PYvQHBc2wMpgB4N+G5dK0EPVSyMCy7HKBtK44kqEVBtgal+UStI/UA
    FkBBkG578eFsEDSMDPUaUKNUj4lo7xRTqlrllukXqVe0EiSvoiOSCIb7pXqLiSOO
    857wHnmxQ1XuDR9kbHubukXQCUswGqnSJXMmwzEBAoGBAIRBMoYfrloWgLH2pc+0
    svQXlAkVP9kTYnMyor95WxuyId7XEfJ05zQBXjT+J5444LTQPo7aqTiWghWptHP9
    fX2znu1ZJee3/0TpekFodUNSsBKYQTf1LDIhwV7jSMXUyL/FrIKeXldk+H+waGXQ
    Xesy3EzU3dOGDMgKmNyyvgFt
    -----END PRIVATE KEY-----
  key-id: gw-1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO

    # === SPRING WEBFLUX ===
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG

    # === SPRING SECURITY ===
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.oauth2: DEBUG

    # === WEB / MVC ===
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: WARN

    # === SPRING BOOT ===
    org.springframework.boot.autoconfigure: INFO

    # === JACKSON / JSON ===
    com.fasterxml.jackson.databind: INFO

    # === HTTP CLIENT / FEIGN ===
    feign: DEBUG
    feign.Logger: DEBUG

    # === TRANSACTIONS ===
    org.springframework.transaction: INFO

    # === HIBERNATE (if JPA) ===
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE