server:
  port: 8888

keycloak:
  server-url: http://localhost:8080
  realm: marketsync-client
  client-id: iam-service
  client-secret: dOku5o71hY0AvQWrUeVdeQ90ScQsyjUn

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/marketsync-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
