server:
  port: 8888

keycloak:
  server-url: http://localhost:8080
  realm: marketsync-client
  client-id: iam-service
  client-secret: gY7znkInLrtlGiHEELh1ZalNU9SZRhYN

internal-jwt:
  issuer: marketsync-gateway
  audience: marketsync-internal
  public-key-pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HglAoDsfRTORBkzAAQk
    nfhPoINcSZKOtvqH3mNSKYfXGUcRf0JVPONbMaLbC391N8quD8MkXXOr703mp60v
    cvuRH4zsAQ/4kAitdMvEeDvzWqjVWAx61B19byQmVlC9D24kab36TcK66MrvrBpt
    nm6xq4V6MfN0c+ETBKs3a5AmYDJYR6BTjkyyv72okYlc5RdW52I+p8oQQCxzv9nH
    v87AsUuWHMqedf8uVetACwyMrK1kC/4LbNW5z9M5q8CIg1H07oZxZ/KE0N9yVvyc
    BB03TRXk+WvG2DQ7g+2ECEt8uhuhOB/3lhiaMjPYLkfKyfgs4pFGCTEwDhAP6jm+
    EQIDAQAB
    -----END PUBLIC KEY-----

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO

    # === SPRING SECURITY ===
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.oauth2: DEBUG

    # === WEB / MVC ===
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: WARN

    # === SPRING BOOT ===
    org.springframework.boot.autoconfigure: INFO

    # === JACKSON / JSON ===
    com.fasterxml.jackson.databind: INFO

    # === HTTP CLIENT / FEIGN ===
    feign: DEBUG
    feign.Logger: DEBUG

    # === TRANSACTIONS ===
    org.springframework.transaction: INFO

    # === HIBERNATE (if JPA) ===
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE