server:
  port: 8900

schedule:
  time-ms: 5000
  fetch-page-size-per-round: 5

kafka:
  enabled: true

spring:
  mongodb:
    uri: mongodb://subscription:subscription@localhost:27018/subscription?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  config:
    finance-url: http://localhost:8800/api/v1/finances

send-email-topic: send-email-topic

internal-jwt:
  issuer: marketsync-gateway
  audience: marketsync-internal
  public-key-pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HglAoDsfRTORBkzAAQk
    nfhPoINcSZKOtvqH3mNSKYfXGUcRf0JVPONbMaLbC391N8quD8MkXXOr703mp60v
    cvuRH4zsAQ/4kAitdMvEeDvzWqjVWAx61B19byQmVlC9D24kab36TcK66MrvrBpt
    nm6xq4V6MfN0c+ETBKs3a5AmYDJYR6BTjkyyv72okYlc5RdW52I+p8oQQCxzv9nH
    v87AsUuWHMqedf8uVetACwyMrK1kC/4LbNW5z9M5q8CIg1H07oZxZ/KE0N9yVvyc
    BB03TRXk+WvG2DQ7g+2ECEt8uhuhOB/3lhiaMjPYLkfKyfgs4pFGCTEwDhAP6jm+
    EQIDAQAB
    -----END PUBLIC KEY-----

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO

    # === SPRING SECURITY ===
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.oauth2: DEBUG

    # === WEB / MVC ===
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: WARN

    # === SPRING BOOT ===
    org.springframework.boot.autoconfigure: INFO

    # === JACKSON / JSON ===
    com.fasterxml.jackson.databind: INFO

    # === HTTP CLIENT / FEIGN ===
    feign: DEBUG
    feign.Logger: DEBUG

    # === TRANSACTIONS ===
    org.springframework.transaction: INFO

    # === HIBERNATE (if JPA) ===
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE