server:
  port: 8200

spring:
  datasource:
    username: wallet
    password: wallet
    url: jdbc:postgresql://localhost/wallet?sslmode=disable
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  config:
    finance-url: http://localhost:8800/api/v1/finances

internal-jwt:
  issuer: marketsync-gateway
  audience: wallet-service
  public-key-pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+HglAoDsfRTORBkzAAQk
    nfhPoINcSZKOtvqH3mNSKYfXGUcRf0JVPONbMaLbC391N8quD8MkXXOr703mp60v
    cvuRH4zsAQ/4kAitdMvEeDvzWqjVWAx61B19byQmVlC9D24kab36TcK66MrvrBpt
    nm6xq4V6MfN0c+ETBKs3a5AmYDJYR6BTjkyyv72okYlc5RdW52I+p8oQQCxzv9nH
    v87AsUuWHMqedf8uVetACwyMrK1kC/4LbNW5z9M5q8CIg1H07oZxZ/KE0N9yVvyc
    BB03TRXk+WvG2DQ7g+2ECEt8uhuhOB/3lhiaMjPYLkfKyfgs4pFGCTEwDhAP6jm+
    EQIDAQAB
    -----END PUBLIC KEY-----

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

wallet:
  websocket:
    refresh-interval-ms: 5000 # 5 second interval

frontend-url: http://localhost:4200
