api:
  binance:
    url: https://api.coincap.io/v2/assets/binance-coin
    uri: binance
    fetch-time-ms: 10_000
  bitcoin:
    url: https://api.coincap.io/v2/assets/bitcoin
    uri: bitcoin
    fetch-time-ms: 10_000
  dogecoin:
    url: https://api.coincap.io/v2/assets/dogecoin
    uri: dogecoin
    fetch-time-ms: 10_000
  ethereum:
    url: https://api.coincap.io/v2/assets/ethereum
    uri: ethereum
    fetch-time-ms: 10_000
  solana:
    url: https://api.coincap.io/v2/assets/solana
    uri: solana
    fetch-time-ms: 10_000
  steth:
    url: https://api.coincap.io/v2/assets/steth
    uri: steth
    fetch-time-ms: 10_000
  tether:
    url: https://api.coincap.io/v2/assets/tether
    uri: tether
    fetch-time-ms: 10_000
  tron:
    url: https://api.coincap.io/v2/assets/tron
    uri: tron
    fetch-time-ms: 10_000
  usdcoin:
    url: https://api.coincap.io/v2/assets/usd-coin
    uri: usdcoin
    fetch-time-ms: 10_000
  xrp:
    url: https://api.coincap.io/v2/assets/xrp
    uri: xrp
    fetch-time-ms: 10_000
