eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false # override only provided properties