server:
  port: 8100

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/marketsync
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8880/realms/master/protocol/openid-connect/certs

