server:
  port: 8800

spring:
  data:
    mongodb:
      uri: mongodb://finance:finance@mongodb-finance/finance?authSource=admin&authMechanism=SCRAM-SHA-256&tls=false
      authentication-database: admin

coinmarketcap:
  base-url-page: https://www.coinmarketcap.com/?page=
  crypto-updater-frequency-ms: 60000 # 1 minute
  page-size: 10 # 100 cryptos per page
  jsoup-update-connect-timeout-in-ms: 20000 # 20s
  link-selector: a.cmc-link
  link-attribute: href

  first-section-name-selector: .coin-item-name
  first-section-symbol-selector: .coin-item-symbol
  first-section-price-selector: td[style*='text-align:end'] div[class*='sc-'] span

  second-section-rows-selector: tr.sc-240ce903-0.iPeVVh
  second-section-name-selector: span
  second-section-span-number: 1
  second-section-symbol-selector: .crypto-symbol
  second-section-price-selector: td

wise:
  currency-updater-frequency-ms: 60000 # 60s
  max-fetch-retries: 3
  retry-delay-ms: 5000 # 5s
  base-url: https://wise.com/gb/currency-converter/
  url-separator: -to-
  rate-amount: -rate?amount=1

newconnect:
  update-rate-ms: 600000 # 10 minutes

gpw:
  update-rate-ms: 600000 # 10 minutes