server:
  port: 8800

spring:
  data:
    mongodb:
      host: mongodb-finance
      port: 27017
      username: ${MONGO_FINANCE_USER}
      password: ${MONGO_FINANCE_PASSWORD}
      authentication-database: admin

coingecko:
  api-key: ${COINGECKO_API}
  url: https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=250&page=1
  crypto-updater-frequency-ms: 300000 # 5 minutes

coinmarketcap:
  base-url-page: https://www.coinmarketcap.com/?page=
  crypto-updater-frequency-ms: 60000 # 1 minute
  page-size: 10 # 100 cryptos per page
  jsoup-update-connect-timeout-in-ms: 20000 # 20s
  link-selector: a.cmc-link
  link-attribute: href

  first-section-name-selector: .coin-item-name
  first-section-symbol-selector: .coin-item-symbol
  first-section-price-selector: td[style*='text-align:end'] div[class*='sc-'] span

  second-section-rows-selector: tr.sc-240ce903-0.iPeVVh
  second-section-name-selector: span
  second-section-span-number: 1
  second-section-symbol-selector: .crypto-symbol
  second-section-price-selector: td

wise:
  currency-updater-frequency-ms: 60000 # 60s
  max-fetch-retries: 3
  retry-delay-ms: 5000 # 5s
  base-url: https://wise.com/gb/currency-converter/
  url-separator: -to-
  rate-amount: -rate?amount=1

newconnect:
  update-rate-ms: 600000 # 10 minutes

gpw:
  update-rate-ms: 600000 # 10 minutes

bankier:
  update-rate-ms: 600000 # 10 minutes
