server:
  port: 8800

spring:
  data:
    mongodb:
      uri: mongodb://finance:finance@mongodb-finance/finance?authSource=admin&authMechanism=SCRAM-SHA-256&tls=false
      authentication-database: admin
