server:
  port: 8800

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/marketsync?authSource=admin&authMechanism=SCRAM-SHA-256
      authentication-database: admin
      database: marketsync