server:
  port: 9999

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: finance-service
          uri: lb:http://FINANCE-SERVICE
          predicates:
            - Path=/api/v1/finances/**
        - id: subscription-service
          uri: lb:http://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/subscriptions/**
        - id: wallet-service
          uri: lb:http://WALLET-SERVICE
          predicates:
            - Path=/api/v1/wallets/**
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://keycloak-ms:8080/realms/master/protocol/openid-connect/certs

frontend:
  url: http://localhost:80

management:
  endpoints:
    web:
      exposure:
        include: health,info