server:
  port: 8900

spring:
  data:
    mongodb:
      host: mongodb-subscription
      port: 27017
      username: ${MONGO_SUBSCRIPTION_USER}
      password: ${MONGO_SUBSCRIPTION_PASSWORD}
      authentication-database: admin
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: subscriptionConfirmation:pl.muybien.subscription.kafka.SubscriptionConfirmation

schedule:
  time-ms: 5000
  fetch-page-size-per-round: 5

application:
  config:
    finance-url: ${FINANCE_API_URL}

send-notification-topic: send-notification-topic