server:
  port: 8900

schedule:
  time-ms: 5000
  fetch-page-size-per-round: 5

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/marketsync?authSource=admin&authMechanism=SCRAM-SHA-256
      authentication-database: admin
      database: marketsync

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: subscriptionConfirmation:pl.muybien.subscription.kafka.SubscriptionConfirmation

application:
  config:
    customer-url: http://customer-server:9999/api/v1/customers
    finance-url: http://finance-server:9999/api/v1/finances

send-email-topic: send-email-topic
