server:
  port: 8200

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://postgres:5432/marketsync
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://eureka-server:9999/api/v1/customers
    finance-url: http://eureka-server:9999/api/v1/finances