server:
  port: 8200

spring:
  datasource:
    username: wallet
    password: wallet
    url: jdbc:postgresql://postgres-wallet/wallet?sslmode=disable
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    finance-url: http://finance-server:8800/api/v1/finances