server:
  port: 9999

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: iam-service
              uri: http://iam-server:8888
              predicates:
                - Path=/api/v1/iam/**
            - id: user-service
              uri: http://user-server:8000
              predicates:
                - Path=/api/v1/users/**
            - id: finance-service
              uri: http://finance-server:8800
              predicates:
                - Path=/api/v1/finances/**
            - id: subscription-service
              uri: http://subscription-server:8900
              predicates:
                - Path=/api/v1/subscriptions/**
            - id: wallet-service
              uri: http://wallet-server:8200
              predicates:
                - Path=/api/v1/wallets/**
            - id: wallet-ws
              uri: http://wallet-server:8200
              predicates:
                - Path=/api/ws-wallet/**

  security:
    oauth2:
      resourceserver:
        issuer-uri: ${KEYCLOAK_ISSUER_URL}

frontend-url: ${FRONTEND_URL}

jwk-uri: ${JWK_URI}

internal-jwt:
  issuer: marketsync-gateway
  ttl-seconds: 90
  audience: marketsync-internal
  public-key-pem: ${PUBLIC_KEY_PEM}
  private-key-pem: ${PRIVATE_KEY_PEM}
  key-id: gw-1

management:
  endpoints:
    web:
      exposure:
        include: health,info