server:
  port: 8888

keycloak:
  server-url: http://keycloak:8080
  realm: ${KC_REALM}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/${KC_REALM}

management:
  endpoints:
    web:
      exposure:
        include: health,info