server:
  port: 8000

spring:
  datasource:
    username: ${POSTGRES_USER_USER}
    password: ${POSTGRES_USER_PASSWORD}
    url: jdbc:postgresql://postgres-user/${POSTGRES_USER_DB}?sslmode=disable
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    iam-url: http://iam-service:8888/api/v1/iam

management:
  endpoints:
    web:
      exposure:
        include: health,info