server:
  port: 7777

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/configurations
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
