export enum CurrencyType {
    ADA = 'ADA',
    AED = 'AED',
    AFN = 'AFN',
    ALL = 'ALL',
    AMD = 'AMD',
    ANG = 'ANG',
    AOA = 'AOA',
    ARB = 'ARB',
    ARS = 'ARS',
    AUD = 'AUD',
    AVAX = 'AVAX',
    AWG = 'AWG',
    AZN = 'AZN',
    BAM = 'BAM',
    BBD = 'BBD',
    BDT = 'BDT',
    BGN = 'BGN',
    BHD = 'BHD',
    BIF = 'BIF',
    BMD = 'BMD',
    BNB = 'BNB',
    BND = 'BND',
    BOB = 'BOB',
    BRL = 'BRL',
    BSD = 'BSD',
    BTC = 'BTC',
    BTN = 'BTN',
    BWP = 'BWP',
    BYN = 'BYN',
    BYR = 'BYR',
    BZD = 'BZD',
    CAD = 'CAD',
    CDF = 'CDF',
    CHF = 'CHF',
    CLF = 'CLF',
    CLP = 'CLP',
    CNY = 'CNY',
    COP = 'COP',
    CRC = 'CRC',
    CUC = 'CUC',
    CUP = 'CUP',
    CVE = 'CVE',
    CZK = 'CZK',
    DAI = 'DAI',
    DJF = 'DJF',
    DKK = 'DKK',
    DOP = 'DOP',
    DOT = 'DOT',
    DZD = 'DZD',
    EGP = 'EGP',
    ERN = 'ERN',
    ETB = 'ETB',
    ETH = 'ETH',
    EUR = 'EUR',
    FJD = 'FJD',
    FKP = 'FKP',
    GBP = 'GBP',
    GEL = 'GEL',
    GGP = 'GGP',
    GHS = 'GHS',
    GIP = 'GIP',
    GMD = 'GMD',
    GNF = 'GNF',
    GTQ = 'GTQ',
    GYD = 'GYD',
    HKD = 'HKD',
    HNL = 'HNL',
    HRK = 'HRK',
    HTG = 'HTG',
    HUF = 'HUF',
    IDR = 'IDR',
    ILS = 'ILS',
    IMP = 'IMP',
    INR = 'INR',
    IQD = 'IQD',
    IRR = 'IRR',
    ISK = 'ISK',
    JEP = 'JEP',
    JMD = 'JMD',
    JOD = 'JOD',
    JPY = 'JPY',
    KES = 'KES',
    KGS = 'KGS',
    KHR = 'KHR',
    KMF = 'KMF',
    KPW = 'KPW',
    KRW = 'KRW',
    KWD = 'KWD',
    KYD = 'KYD',
    KZT = 'KZT',
    LAK = 'LAK',
    LBP = 'LBP',
    LKR = 'LKR',
    LRD = 'LRD',
    LSL = 'LSL',
    LTC = 'LTC',
    LTL = 'LTL',
    LVL = 'LVL',
    LYD = 'LYD',
    MAD = 'MAD',
    MATIC = 'MATIC',
    MDL = 'MDL',
    MGA = 'MGA',
    MKD = 'MKD',
    MMK = 'MMK',
    MNT = 'MNT',
    MOP = 'MOP',
    MRO = 'MRO',
    MRU = 'MRU',
    MUR = 'MUR',
    MVR = 'MVR',
    MWK = 'MWK',
    MXN = 'MXN',
    MYR = 'MYR',
    MZN = 'MZN',
    NAD = 'NAD',
    NGN = 'NGN',
    NIO = 'NIO',
    NOK = 'NOK',
    NPR = 'NPR',
    NZD = 'NZD',
    OMR = 'OMR',
    OP = 'OP',
    PAB = 'PAB',
    PEN = 'PEN',
    PGK = 'PGK',
    PHP = 'PHP',
    PKR = 'PKR',
    PLN = 'PLN',
    PYG = 'PYG',
    QAR = 'QAR',
    RON = 'RON',
    RSD = 'RSD',
    RUB = 'RUB',
    RWF = 'RWF',
    SAR = 'SAR',
    SBD = 'SBD',
    SCR = 'SCR',
    SDG = 'SDG',
    SEK = 'SEK',
    SGD = 'SGD',
    SHP = 'SHP',
    SLE = 'SLE',
    SLL = 'SLL',
    SOL = 'SOL',
    SOS = 'SOS',
    SRD = 'SRD',
    STD = 'STD',
    STN = 'STN',
    SVC = 'SVC',
    SYP = 'SYP',
    SZL = 'SZL',
    THB = 'THB',
    TJS = 'TJS',
    TMT = 'TMT',
    TND = 'TND',
    TOP = 'TOP',
    TRY = 'TRY',
    TTD = 'TTD',
    TWD = 'TWD',
    TZS = 'TZS',
    UAH = 'UAH',
    UGX = 'UGX',
    USD = 'USD',
    USDC = 'USDC',
    USDT = 'USDT',
    UYU = 'UYU',
    UZS = 'UZS',
    VEF = 'VEF',
    VES = 'VES',
    VND = 'VND',
    VUV = 'VUV',
    WST = 'WST',
    XAF = 'XAF',
    XAG = 'XAG',
    XAU = 'XAU',
    XCD = 'XCD',
    XDR = 'XDR',
    XOF = 'XOF',
    XPD = 'XPD',
    XPF = 'XPF',
    XPT = 'XPT',
    XRP = 'XRP',
    YER = 'YER',
    ZAR = 'ZAR',
    ZMK = 'ZMK',
    ZMW = 'ZMW',
    ZWG = 'ZWG',
    ZWL = 'ZWL',
}

export namespace CurrencyType {
    export const Symbols: Record<CurrencyType, string> = {
        [CurrencyType.ADA]: 'ADA',
        [CurrencyType.AED]: 'د.إ',
        [CurrencyType.AFN]: '؋',
        [CurrencyType.ALL]: 'L',
        [CurrencyType.AMD]: '֏',
        [CurrencyType.ANG]: 'ƒ',
        [CurrencyType.AOA]: 'Kz',
        [CurrencyType.ARB]: 'ARB',
        [CurrencyType.ARS]: '$',
        [CurrencyType.AUD]: 'A$',
        [CurrencyType.AVAX]: 'AVAX',
        [CurrencyType.AWG]: 'ƒ',
        [CurrencyType.AZN]: '₼',
        [CurrencyType.BAM]: 'KM',
        [CurrencyType.BBD]: 'Bds$',
        [CurrencyType.BDT]: '৳',
        [CurrencyType.BGN]: 'лв',
        [CurrencyType.BHD]: 'ب.د',
        [CurrencyType.BIF]: 'FBu',
        [CurrencyType.BMD]: 'BD$',
        [CurrencyType.BNB]: 'BNB',
        [CurrencyType.BND]: 'B$',
        [CurrencyType.BOB]: 'Bs.',
        [CurrencyType.BRL]: 'R$',
        [CurrencyType.BSD]: 'B$',
        [CurrencyType.BTC]: '₿',
        [CurrencyType.BTN]: 'Nu.',
        [CurrencyType.BWP]: 'P',
        [CurrencyType.BYN]: 'Br',
        [CurrencyType.BYR]: 'Br',
        [CurrencyType.BZD]: 'BZ$',
        [CurrencyType.CAD]: 'C$',
        [CurrencyType.CDF]: 'FC',
        [CurrencyType.CHF]: 'CHF',
        [CurrencyType.CLF]: 'CLF',
        [CurrencyType.CLP]: '$',
        [CurrencyType.CNY]: '¥',
        [CurrencyType.COP]: '$',
        [CurrencyType.CRC]: '₡',
        [CurrencyType.CUC]: 'CUC',
        [CurrencyType.CUP]: '₱',
        [CurrencyType.CVE]: '$',
        [CurrencyType.CZK]: 'Kč',
        [CurrencyType.DAI]: 'DAI',
        [CurrencyType.DJF]: 'Fdj',
        [CurrencyType.DKK]: 'kr',
        [CurrencyType.DOP]: 'RD$',
        [CurrencyType.DOT]: 'DOT',
        [CurrencyType.DZD]: 'د.ج',
        [CurrencyType.EGP]: 'E£',
        [CurrencyType.ERN]: 'Nfk',
        [CurrencyType.ETB]: 'Br',
        [CurrencyType.ETH]: 'Ξ',
        [CurrencyType.EUR]: '€',
        [CurrencyType.FJD]: 'FJ$',
        [CurrencyType.FKP]: '£',
        [CurrencyType.GBP]: '£',
        [CurrencyType.GEL]: '₾',
        [CurrencyType.GGP]: '£',
        [CurrencyType.GHS]: '₵',
        [CurrencyType.GIP]: '£',
        [CurrencyType.GMD]: 'D',
        [CurrencyType.GNF]: 'FG',
        [CurrencyType.GTQ]: 'Q',
        [CurrencyType.GYD]: 'GY$',
        [CurrencyType.HKD]: 'HK$',
        [CurrencyType.HNL]: 'L',
        [CurrencyType.HRK]: 'kn',
        [CurrencyType.HTG]: 'G',
        [CurrencyType.HUF]: 'Ft',
        [CurrencyType.IDR]: 'Rp',
        [CurrencyType.ILS]: '₪',
        [CurrencyType.IMP]: '£',
        [CurrencyType.INR]: '₹',
        [CurrencyType.IQD]: 'ع.د',
        [CurrencyType.IRR]: '﷼',
        [CurrencyType.ISK]: 'kr',
        [CurrencyType.JEP]: '£',
        [CurrencyType.JMD]: 'J$',
        [CurrencyType.JOD]: 'د.ا',
        [CurrencyType.JPY]: '¥',
        [CurrencyType.KES]: 'KSh',
        [CurrencyType.KGS]: 'с',
        [CurrencyType.KHR]: '៛',
        [CurrencyType.KMF]: 'CF',
        [CurrencyType.KPW]: '₩',
        [CurrencyType.KRW]: '₩',
        [CurrencyType.KWD]: 'د.ك',
        [CurrencyType.KYD]: 'CI$',
        [CurrencyType.KZT]: '₸',
        [CurrencyType.LAK]: '₭',
        [CurrencyType.LBP]: 'ل.ل',
        [CurrencyType.LKR]: 'Rs',
        [CurrencyType.LRD]: 'L$',
        [CurrencyType.LSL]: 'L',
        [CurrencyType.LTC]: 'Ł',
        [CurrencyType.LTL]: 'Lt',
        [CurrencyType.LVL]: 'Ls',
        [CurrencyType.LYD]: 'ل.د',
        [CurrencyType.MAD]: 'د.م.',
        [CurrencyType.MATIC]: 'MATIC',
        [CurrencyType.MDL]: 'L',
        [CurrencyType.MGA]: 'Ar',
        [CurrencyType.MKD]: 'ден',
        [CurrencyType.MMK]: 'Ks',
        [CurrencyType.MNT]: '₮',
        [CurrencyType.MOP]: 'MOP$',
        [CurrencyType.MRO]: 'UM',
        [CurrencyType.MRU]: 'UM',
        [CurrencyType.MUR]: '₨',
        [CurrencyType.MVR]: 'Rf',
        [CurrencyType.MWK]: 'MK',
        [CurrencyType.MXN]: 'Mex$',
        [CurrencyType.MYR]: 'RM',
        [CurrencyType.MZN]: 'MT',
        [CurrencyType.NAD]: 'N$',
        [CurrencyType.NGN]: '₦',
        [CurrencyType.NIO]: 'C$',
        [CurrencyType.NOK]: 'kr',
        [CurrencyType.NPR]: 'Rs',
        [CurrencyType.NZD]: 'NZ$',
        [CurrencyType.OMR]: 'ر.ع.',
        [CurrencyType.OP]: 'OP',
        [CurrencyType.PAB]: 'B/.',
        [CurrencyType.PEN]: 'S/.',
        [CurrencyType.PGK]: 'K',
        [CurrencyType.PHP]: '₱',
        [CurrencyType.PKR]: '₨',
        [CurrencyType.PLN]: 'zł',
        [CurrencyType.PYG]: '₲',
        [CurrencyType.QAR]: 'ر.ق',
        [CurrencyType.RON]: 'lei',
        [CurrencyType.RSD]: 'din',
        [CurrencyType.RUB]: '₽',
        [CurrencyType.RWF]: 'FRw',
        [CurrencyType.SAR]: 'ر.س',
        [CurrencyType.SBD]: 'SI$',
        [CurrencyType.SCR]: '₨',
        [CurrencyType.SDG]: 'ج.س.',
        [CurrencyType.SEK]: 'kr',
        [CurrencyType.SGD]: 'S$',
        [CurrencyType.SHP]: '£',
        [CurrencyType.SLE]: 'SLE',
        [CurrencyType.SLL]: 'Le',
        [CurrencyType.SOL]: 'SOL',
        [CurrencyType.SOS]: 'Sh',
        [CurrencyType.SRD]: '$',
        [CurrencyType.STD]: 'Db',
        [CurrencyType.STN]: 'Db',
        [CurrencyType.SVC]: '₡',
        [CurrencyType.SYP]: '£',
        [CurrencyType.SZL]: 'L',
        [CurrencyType.THB]: '฿',
        [CurrencyType.TJS]: 'ЅМ',
        [CurrencyType.TMT]: 'm',
        [CurrencyType.TND]: 'د.ت',
        [CurrencyType.TOP]: 'T$',
        [CurrencyType.TRY]: '₺',
        [CurrencyType.TTD]: 'TT$',
        [CurrencyType.TWD]: 'NT$',
        [CurrencyType.TZS]: 'TSh',
        [CurrencyType.UAH]: '₴',
        [CurrencyType.UGX]: 'USh',
        [CurrencyType.USD]: '$',
        [CurrencyType.USDC]: 'USDC',
        [CurrencyType.USDT]: 'USDT',
        [CurrencyType.UYU]: '$U',
        [CurrencyType.UZS]: 'лв',
        [CurrencyType.VEF]: 'Bs.',
        [CurrencyType.VES]: 'Bs.',
        [CurrencyType.VND]: '₫',
        [CurrencyType.VUV]: 'VT',
        [CurrencyType.WST]: 'WS$',
        [CurrencyType.XAF]: 'FCFA',
        [CurrencyType.XAG]: 'XAG',
        [CurrencyType.XAU]: 'XAU',
        [CurrencyType.XCD]: 'EC$',
        [CurrencyType.XDR]: 'XDR',
        [CurrencyType.XOF]: 'CFA',
        [CurrencyType.XPD]: 'XPD',
        [CurrencyType.XPF]: '₣',
        [CurrencyType.XPT]: 'XPT',
        [CurrencyType.XRP]: 'XRP',
        [CurrencyType.YER]: '﷼',
        [CurrencyType.ZAR]: 'R',
        [CurrencyType.ZMK]: 'ZK',
        [CurrencyType.ZMW]: 'ZK',
        [CurrencyType.ZWG]: 'ZWG',
        [CurrencyType.ZWL]: 'Z$',
    };
}
